services:
  gitlab-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: gitlab-proxy
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=client
    platform: linux/amd64
    tty: true
    stdin_open: true